log_keywords: None
model:
  target: modules.model.InfiniteNature
  seed: 0
  gpu_ids: 0,1,  # -1 for cpu, make sure there is comma follows each number
  params:
    ckpt_path: /home/yuan/PycharmProjects/InfiniteNature_pytorch/trained_models/google_earth/last.ckpt
    learning_rate: 1e-4
    discriminative_loss_start_step: 0
    generator_config:
      embedding_size: 256
      use_spectral_norm: False
      num_channel: 32
      num_hidden: 128
      dataset: google_earth
    ignore_keys: [dense, perceptual_loss, spade_discriminator_1, spade_discriminator_0]

data:
  target: infiniate_nature_data.utils.utils.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 0
    dataset: google_earth
    depth_range: [ 0.099975586, 4.765625 ]
    dataset_dir: /projects/percetion/datasets/GoogleEarthDataset #/media/yuan/T7_red/GoogleEarthDataset
    use_depth: True
    image_resolution: [512, 512]
