log_keywords: model.params.learning_rate
model:
  target: modules.model.InfiniteNature
  seed: 0
  gpu_ids: 0,   # -1 for cpu, make sure there is comma follows each number
  params:
    ckpt_path: /home/yuan/PycharmProjects/InfiniteNature_pytorch/trained_models/clevr-infinite/last.ckpt
    learning_rate: 1e-4
    discriminative_loss_start_step: 0
    generator_config:
      embedding_size: 256
      use_spectral_norm: False
      num_channel: 32
      num_hidden: 128
      dataset: clevr-infinite
    ignore_keys: [dense, perceptual_loss, spade_discriminator_0, spade_discriminator_1]

data:
  target: infiniate_nature_data.utils.utils.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    dataset: clevr-infinite
    depth_range: [ 7, 16 ]
    dataset_dir: /projects/perception/datasets/blender_3d_large #/media/yuan/T7_red/blender_3d_large
    use_depth: True
    image_resolution: [256, 256]
