log_keywords: data.params.novel_view_num, data.params.init_method, model.params.cache_config.sigma_start_index, model.params.loss_config.flow_loss_weight, model.params.loss_config.diffusion_loss_weight, model.params.loss_config.image_loss_weight

model:
  target: modules.models.InfiniteNature
  seed: 0
  gpu_ids: 0, # -1 for cpu, make sure there is comma follows each number
  params:
    learning_rate: 1e-3
    generator_config:
      flow_loss_weight: 1
    loss_config:
      flow_loss_weight: 1
      flow_loss_start_sigma_index: 850
      diffusion_loss_weight: 1
      image_loss_weight: 100
      image_loss_start_sigma_index: 850

data:
  target: data.utils.utils.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 0
    n_src: 1
    dataset: google_earth
    depth_range: [ 0.1, 30 ]
    phase: conditional_generation # should be the same as model.phase parameter
    dataset_dir: /media/yuan/T7_red/GoogleEarthDataset
    use_depth: True
    image_resolution: [64, 64]