log_keywords: None
model:
  target: modules.model.InfiniteNature
  seed: 0
  gpu_ids: 0,   # -1 for cpu, make sure there is comma follows each number
  params:
    learning_rate: 2e-4
    generator_config:
      embedding_size: 256
      use_spectral_norm: False
      num_channel: 32
      num_hidden: 128
      dataset: google_earth
    ignore_keys: linear,

data:
  target: data.utils.utils.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 0
    dataset: google_earth
    depth_range: [ 0.099975586, 4.765625 ]
    dataset_dir: /media/yuan/T7_red/GoogleEarthDataset
    use_depth: True
    image_resolution: [512, 512]